# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000
# default: &default
  # adapter: mysql2
  # encoding: utf8
  # pool: 5
  # username:　root
  # password:　2910831Ryu

default: &default
  adapter: mysql2
  host: localhost
  database: demo_dev
  username: root
  password: 2910831Ryu
  encoding: utf8
  pool: 5

development:
  adapter: mysql2
  host: localhost
  database: demo_dev
  username: root
  password: 2910831Ryu
  encoding: utf8
  pool: 5

test:
  adapter: mysql2
  host: localhost
  username: root
  password: 2910831Ryu
  encoding: utf8
  pool: 5
  database: demo_test

production:
  adapter: mysql2
  host: localhost
  username: root
  password:
  encoding: utf8
  pool: 5
  database: demo_prod
